# Background and foreground colors
background = #161616
foreground = #f2f4f8

# Standard colors
palette = 0=#161616
palette = 1=#ee5396
palette = 2=#33b1ff
palette = 3=#08bdba
palette = 4=#78a9ff
palette = 5=#be95ff
palette = 6=#25be6a
palette = 7=#f2f4f8

# Bright colors
palette = 8=#484848
palette = 9=#f16da6
palette = 10=#52bdff
palette = 11=#2dc7c4
palette = 12=#8cb6ff
palette = 13=#c8a5ff
palette = 14=#46c880
palette = 15=#e4e4e5
