$color = rgba(22, 22, 22, 1)
$inner_color = rgba(22, 22, 22, 0.66)
$outer_color = rgba(190, 149, 255, 1)
$font_color = rgba(242, 244, 248, 1)
$placeholder_color = rgba(242, 244, 248, 0.7)
$check_color = rgba(37, 190, 106, 1)
