#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --add event yabai_space_labels_refresh

sketchybar --remove '/.*/' >/dev/null 2>&1 || true

sketchybar --bar height=37        \
                 blur_radius=0    \
                 display=all      \
                 position=top     \
                 sticky=on        \
                 padding_left=10  \
                 padding_right=10 \
                 color=0x00000000

sketchybar --load-font "$HOME/Library/Fonts/sketchybar-app-font.ttf"

sketchybar --default icon.font="SF Pro:Semibold:15.0"   \
                     icon.color=$TEXT_COLOR             \
                     label.font="SF Pro:Semibold:12.0"  \
                     label.color=$TEXT_COLOR            \
                     background.color=0x00000000        \
                     background.border_color=0x33ffffff \
                     background.border_width=1          \
                     background.drawing=on              \
                     background.corner_radius=5         \
                     background.height=24               \
                     padding_left=5                     \
                     padding_right=5                    \
                     label.y_offset=1                   \
                     label.padding_left=4               \
                     label.padding_right=10             \
                     icon.padding_left=10               \
                     icon.padding_right=4

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/ram.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --update
