#!/usr/bin/env bash

# Bar
BAR_POSITION="top"
BAR_MARGIN=0
BAR_Y_OFFSET=0
BAR_HIDDEN_Y_OFFSET=-40
BAR_CORNER_RADIUS=0
BAR_HEIGHT=37
BAR_COLOR="0x00000000"
BAR_BLUR_RADIUS=24
BAR_PADDING_LEFT=12
BAR_PADDING_RIGHT=12
BAR_TOPMOST="window"
BAR_TRIGGER_ZONE=34
BAR_VISIBILITY_POLL_INTERVAL=0.05

# Defaults
ITEM_PADDING_LEFT=6
ITEM_PADDING_RIGHT=6
ICON_FONT="JetBrainsMono Nerd Font:Regular:13.0"
LABEL_FONT="SF Pro Display:Semibold:13.0"
SYMBOL_FONT="JetBrainsMono Nerd Font:Regular:14.0"
METRIC_TOKEN_FONT="SF Pro Display:Heavy:10.5"
ITEM_BACKGROUND_DRAWING="on"
ITEM_BG_ALPHA="16"
ITEM_BORDER_ALPHA="20"
ITEM_BORDER_WIDTH=1
ITEM_BG_RADIUS=9
ITEM_BG_HEIGHT=29
ITEM_BG_BLUR_RADIUS=30
ICON_PADDING_LEFT=10
ICON_PADDING_RIGHT=5
LABEL_PADDING_LEFT=4
LABEL_PADDING_RIGHT=10

# Colors
ACCENT_COLOR="0xffffff00"
TEXT_COLOR="0xffdacbe6"
SUCCESS_COLOR="0xff34C759"
WARNING_COLOR="0xffFFD60A"

# Items
SPACE_COUNT=6
SPACE_ITEM_WIDTH=86
SPACE_LABEL_WIDTH=50
SPACE_ICON_LIMIT=3
SPACE_UPDATE_FREQ=2
SPACE_LABEL_FONT="sketchybar-app-font:Regular:14.0"
CLOCK_ICON="󰃭"
BATTERY_ICON=""
RAM_ICON="RAM"
CPU_ICON="CPU"
CLOCK_DATE_FORMAT="+%a %d %b · %I:%M %p"
CLOCK_UPDATE_FREQ=30
BATTERY_UPDATE_FREQ=120
RAM_UPDATE_FREQ=10
CPU_UPDATE_FREQ=10
