background = #000000
foreground = #F0F6FF

cursor-color = #66CCFF
cursor-text = #000000

selection-background = #123A4D
selection-foreground = #F0F6FF

window-padding-y = 8,8
window-padding-x = 8,8
window-padding-balance = true

# normal colors
palette = 0=#050505
palette = 1=#FF3366
palette = 2=#33FFDD
palette = 3=#3399FF
palette = 4=#1E90FF
palette = 5=#00CFFF
palette = 6=#66CCFF
palette = 7=#F0F6FF

# bright colors
palette = 8=#333333
palette = 9=#FF6688
palette = 10=#66FFE6
palette = 11=#66B3FF
palette = 12=#66B2FF
palette = 13=#33DDFF
palette = 14=#99DDFF
palette = 15=#FFFFFF
