#!/usr/bin/env bash

macarchy_apply_borders() {
    local generated="$MACARCHY_CONFIG_HOME/macarchy/generated/borders.conf"
    local borders_bin

    borders_bin="$(macarchy_command borders || true)"
    [[ -f "$MACARCHY_CONFIG_HOME/borders/bordersrc" || -n "$borders_bin" ]] || return 0

    macarchy_atomic_write "$generated" <<EOF
active_color="$THEME_BORDER_ACTIVE"
inactive_color="$THEME_BORDER_INACTIVE"
width="$THEME_BORDER_WIDTH"
blacklist="iPhone Mirroring"
EOF

    if [[ -n "$borders_bin" ]] && pgrep -x borders >/dev/null 2>&1; then
        "$borders_bin" active_color="$THEME_BORDER_ACTIVE" \
            inactive_color="$THEME_BORDER_INACTIVE" width="$THEME_BORDER_WIDTH" >/dev/null 2>&1 || true
    fi
    macarchy_info "  Borders: $THEME_BORDER_ACTIVE"
}

macarchy_apply_sketchybar() {
    local config_dir="$MACARCHY_CONFIG_HOME/sketchybar"
    local theme_file="$config_dir/theme.sh"
    local sketchybar_bin

    [[ -d "$config_dir" ]] || return 0
    macarchy_atomic_write "$theme_file" <<EOF
#!/usr/bin/env bash
ACCENT_COLOR="$THEME_BORDER_ACTIVE"
TEXT_COLOR="$THEME_SKETCHYBAR_TEXT_COLOR"
BAR_COLOR="$THEME_SKETCHYBAR_BAR_COLOR"
EOF
    chmod 600 "$theme_file"

    sketchybar_bin="$(macarchy_command sketchybar || true)"
    [[ -n "$sketchybar_bin" ]] && "$sketchybar_bin" --reload >/dev/null 2>&1 || true
    macarchy_info "  SketchyBar: colours updated"
}

macarchy_apply_shell() {
    local shell_env="$MACARCHY_THEMES_DIR/.shell-env"
    local accent_hex="${THEME_BORDER_ACTIVE#0xff}"
    local foreground_index=15

    [[ "$THEME_DARK_MODE" == "false" ]] && foreground_index=0
    macarchy_atomic_write "$shell_env" <<EOF
# Generated by theme-switch.
export EZA_COLORS='di=38;5;4:ex=1;38;5;4:ln=38;5;8:xx=38;5;8'
export MACARCHY_ACCENT_IDX='4'
export MACARCHY_FG_IDX='$foreground_index'
export MACARCHY_ACCENT='#$accent_hex'
export MACARCHY_DARK_MODE='$THEME_DARK_MODE'
EOF
    macarchy_info "  Shell: colours updated"
}
