#!/usr/bin/env bash

macarchy_apply_borders() {
    local generated="$MACARCHY_GENERATED_DIR/borders.conf"
    local borders_bin

    borders_bin="$(macarchy_command borders || true)"
    [[ -f "$MACARCHY_CONFIG_HOME/borders/bordersrc" || -n "$borders_bin" ]] || return 0

    if ! macarchy_write_generated "$generated" <<EOF
active_color="$THEME_BORDER_ACTIVE"
inactive_color="$THEME_BORDER_INACTIVE"
width="$THEME_BORDER_WIDTH"
blacklist="iPhone Mirroring"
EOF
    then
        macarchy_error "border colours could not be written"
        return 1
    fi

    if [[ -n "$borders_bin" ]] && pgrep -x borders >/dev/null 2>&1; then
        "$borders_bin" active_color="$THEME_BORDER_ACTIVE" \
            inactive_color="$THEME_BORDER_INACTIVE" width="$THEME_BORDER_WIDTH" >/dev/null 2>&1 || true
    fi
    macarchy_info "  Borders: $THEME_BORDER_ACTIVE"
}

macarchy_apply_sketchybar() {
    local config_dir="$MACARCHY_CONFIG_HOME/sketchybar"
    local theme_file="$config_dir/theme.sh"
    local text_color="${THEME_SKETCHYBAR_TEXT_COLOR:-}"
    local foreground
    local sketchybar_bin

    [[ -d "$config_dir" ]] || return 0
    if [[ -z "$text_color" ]]; then
        foreground="$(macarchy_ghostty_colour "$MACARCHY_THEME_DIR/ghostty.conf" foreground '#ffffff')"
        text_color="0xff${foreground#\#}"
    fi
    if ! macarchy_write_generated "$theme_file" <<EOF
#!/usr/bin/env bash
ACCENT_COLOR="$THEME_BORDER_ACTIVE"
TEXT_COLOR="$text_color"
BAR_COLOR="$THEME_SKETCHYBAR_BAR_COLOR"
EOF
    then
        macarchy_error "SketchyBar colours could not be written"
        return 1
    fi

    sketchybar_bin="$(macarchy_command sketchybar || true)"
    [[ -n "$sketchybar_bin" ]] && "$sketchybar_bin" --reload >/dev/null 2>&1 || true
    macarchy_info "  SketchyBar: colours updated"
}

macarchy_apply_shell() {
    local shell_env="$MACARCHY_GENERATED_DIR/shell-env"
    local border_hex="${THEME_BORDER_ACTIVE#0x}"
    local border_rgb="${border_hex#??}"
    local palette_file="$MACARCHY_THEME_DIR/ghostty.conf"
    local palette4_hex accent_hex accent_index candidate candidate_index
    local foreground_index=15

    [[ "$THEME_DARK_MODE" == "false" ]] && foreground_index=0
    palette4_hex="$(macarchy_ghostty_palette "$palette_file" 4 '#ffffff')"
    accent_index=""
    accent_hex=""
    for candidate in "${THEME_FIREFOX_ACCENT:-}" "#$border_rgb" "$palette4_hex"; do
        [[ "$candidate" =~ ^#[0-9A-Fa-f]{6}$ ]] || continue
        candidate_index="$(macarchy_ghostty_palette_index "$palette_file" "$candidate")"
        [[ -n "$candidate_index" ]] || continue
        accent_index="$candidate_index"
        accent_hex="${candidate#\#}"
        break
    done
    if [[ -z "$accent_index" ]]; then
        accent_index=4
        accent_hex="${palette4_hex#\#}"
    fi
    if ! macarchy_write_generated "$shell_env" <<EOF
# Generated by theme-switch.
export EZA_COLORS='di=38;5;$accent_index:ex=1;38;5;$accent_index:ln=38;5;8:xx=38;5;8'
export MACARCHY_ACCENT_IDX='$accent_index'
export MACARCHY_FG_IDX='$foreground_index'
export MACARCHY_ACCENT='#$accent_hex'
export MACARCHY_DARK_MODE='$THEME_DARK_MODE'
EOF
    then
        macarchy_error "shell theme state could not be written"
        return 1
    fi
    macarchy_info "  Shell: colours updated"
}
