background = #0B0C0C
foreground = #eae9e3
cursor-color = #8e3a59
selection-foreground = #0B0C0C
selection-background = #eae9e3

palette = 0=#0B0C0C
palette = 1=#f24331
palette = 2=#6E6A64
palette = 3=#ed9a1d
palette = 4=#666a6d
palette = 5=#aaa8a4
palette = 6=#EBD698
palette = 7=#CAC8C4
palette = 8=#393e3e
palette = 9=#f24331
palette = 10=#6E6A64
palette = 11=#ed9a1d
palette = 12=#666a6d
palette = 13=#aaa8a4
palette = 14=#EBD698
palette = 15=#f9f9f8
