# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgba(48191bee) rgba(666a6dee) rgba(37393Aee) rgba(0B0C0Cee) rgba(48191bee) 45deg 
    col.inactive_border = rgb(131415)
    gaps_in = 7
    gaps_out = 11
    border_size = 2
}

group {
    col.border_active = $activeBorderColor
}

decoration {
    rounding = 6
    rounding_power = 3
      shadow {
      enabled = yes
      range = 16
      color = rgba(00000088)
    }
}
windowrule = match:class ^(vesktop|Vesktop)$, opacity 1.0 override, no_dim on
windowrule = match:class ^(code|VSCode|VSCodium)$, opacity 1.0 override, no_dim on
windowrule = match:class ^(chromium|Chromium|google-chrome|Brave|brave-browser)$, opacity 1.0 override, no_dim on