$color = rgba(11, 12, 12, 1)
$inner_color = rgba(11, 12, 12, 1)
$outer_color = rgba(67, 69, 73, 1)
$font_color = rgba(185, 185, 185, 1)
$placeholder_color = rgba(185, 185, 185, 0.7)
$check_color = rgba(237, 154, 29, 1)
